python compute_proposition_accurate_rate.py --minute 10 --space 400
python summarize_proposition_accurate_rate.py --minute 10 --space 400
python compute_proposition_accurate_rate.py --minute 15 --space 400
python summarize_proposition_accurate_rate.py --minute 15 --space 400
python compute_proposition_accurate_rate.py --minute 30 --space 400
python summarize_proposition_accurate_rate.py --minute 30 --space 400
python compute_proposition_accurate_rate.py --minute 45 --space 400
python summarize_proposition_accurate_rate.py --minute 45 --space 400
python compute_proposition_accurate_rate.py --minute 5 --space 800
python summarize_proposition_accurate_rate.py --minute 5 --space 800
python compute_proposition_accurate_rate.py --minute 10 --space 800
python summarize_proposition_accurate_rate.py --minute 10 --space 800
python compute_proposition_accurate_rate.py --minute 15 --space 800
python summarize_proposition_accurate_rate.py --minute 15 --space 800
python compute_proposition_accurate_rate.py --minute 30 --space 800
python summarize_proposition_accurate_rate.py --minute 30 --space 800
python compute_proposition_accurate_rate.py --minute 45 --space 800
python summarize_proposition_accurate_rate.py --minute 45 --space 800
python compute_proposition_accurate_rate.py --minute 5 --space 600
python summarize_proposition_accurate_rate.py --minute 5 --space 600
python compute_proposition_accurate_rate.py --minute 10 --space 600
python summarize_proposition_accurate_rate.py --minute 10 --space 600
python compute_proposition_accurate_rate.py --minute 15 --space 600
python summarize_proposition_accurate_rate.py --minute 15 --space 600
python compute_proposition_accurate_rate.py --minute 30 --space 600
python summarize_proposition_accurate_rate.py --minute 30 --space 600
python compute_proposition_accurate_rate.py --minute 45 --space 600
python summarize_proposition_accurate_rate.py --minute 45 --space 600
python compute_proposition_accurate_rate.py --minute 5 --space 1600
python summarize_proposition_accurate_rate.py --minute 5 --space 1600
python compute_proposition_accurate_rate.py --minute 10 --space 1600
python summarize_proposition_accurate_rate.py --minute 10 --space 1600
python compute_proposition_accurate_rate.py --minute 15 --space 1600
python summarize_proposition_accurate_rate.py --minute 15 --space 1600
python compute_proposition_accurate_rate.py --minute 30 --space 1600
python summarize_proposition_accurate_rate.py --minute 30 --space 1600
python compute_proposition_accurate_rate.py --minute 45 --space 1600
python summarize_proposition_accurate_rate.py --minute 45 --space 1600
